export const items = [
    {
      id: 'id1',
      title: "Text",
      discriptions: "Discriptions",
      image: "assets/images.jpg",
      price: 150,
    },
    {
      id: 'id2',
      title: "Textdd",
      discriptions: "Discriptions",
      image: "assets/89-896932_6v-vw-beetle-toy-car-for-kids-png.png",
      price: 150,
    },
    {
      id: 'id3',
      title: "Text",
      discriptions: "Discriptions",
      image: "assets/images.jpg",
      price: 150,
    },
    {
      id: 'id4',
      title: "Text",
      discriptions: "Discriptions",
      image: "assets/images.jpg",
      price: 150,
    },
    {
      id: 'id5',
      title: "Text",
      discriptions: "Discriptions",
      image: "assets/images.jpg",
      price: 150,
    },
    {
      id: 'id6',
      title: "Text",
      discriptions: "Discriptions",
      image: "assets/images.jpg",
      price: 150,
    },
    {
      id: 'id7',
      title: "Text",
      discriptions: "Discriptions",
      image: "assets/images.jpg",
      price: 150,
    },
    {
      id: 'id8',
      title: "Text",
      discriptions: "Discriptions",
      image: "assets/images.jpg",
      price: 150,
    },
    {
      id: 'id9',
      title: "Text",
      discriptions: "Discriptions",
      image: "assets/images.jpg",
      price: 150,
    },
    {
      id: 'id10',
      title: "Text",
      discriptions: "Discriptions",
      image: "assets/images.jpg",
      price: 150,
    },
    {
      id: 'id11',
      title: "Text",
      discriptions: "Discriptions",
      image: "assets/images.jpg",
      price: 150,
    },
  ];